version: "3.8"

services:
  db:
    image: postgres
    container_name: pg
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    # volumes:
    #   - <your-path>/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
