from flask_security import UserMixin
from src.utils.db import db
from src.models.user_roles import UserRoles


class User(db.Model, UserMixin):
    """
    User model for database

    :param id: integer, primary key, auto increment
    :param username: string, use email as username
    :param password: string, at least 8 characters, one letter and one number is required
    :param email: string
    :param name: string
    :param active: boolean, default false
    :param roles: list of roles
    :param fs_uniquifier: string, auto generated by flask-security
    """
    id = db.Column(db.BigInteger(), primary_key=True, autoincrement=True)
    username = db.Column(db.String(30), unique=True, nullable=False)
    password = db.Column(db.String(255))
    email = db.Column(db.String(100), unique=True, nullable=False)
    name = db.Column(db.String(80), nullable=False)
    active = db.Column(db.Boolean(), default=False)
    roles = db.relationship('Role', secondary=UserRoles.__tablename__,
                            backref=db.backref('user', lazy='dynamic'))
    fs_uniquifier = db.Column(db.String, nullable=False, unique=True)
